#!/usr/bin/env bash
set -o pipefail
set -o errexit
set -o nounset
set -o verbose
set -o xtrace

cd $TRAVIS_BUILD_DIR
git config user.name "Travis CI"
git config user.email "travis@rob.ot"

./make-root-tar.sh |& tee root-build.log

git add root-build.log
#git add root.tar.gz
curl -F file=@root.tar.gz -F expires=2w -F no_index=true https://api.anonymousfiles.io/

chmod 600 travis_key
eval `ssh-agent -s`

ssh-add travis_key

git commit -m "$(date -u -I): rootfs built via travis"

export GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

git remote set-url --push origin git@github.com:greyltc/archlinux-bootstrapper.git

TAG="$(date -u -I)"
git tag --annotate --force --message="${TAG} generated by travis" "${TAG}" master
#ssh-add -l
#ssh-add -L
git config --local lfs.https://github.com/.locksverify false
git push origin master --force --tags
